include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    directives_ordering: true
    prefer_final_locals: true
    sort_constructors_first: true
    unawaited_futures: true

